version: 2.1
orbs:
  node: circleci/node@3.0.0

  jobs:
    run_test:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - node/install:
            install-yarn: true
        - run: node --version

workflows:
  build_tests:
    jobs:
      - run_test
